using System;

namespace OrkaToken.Model.STK
{
    public class STK_STOKKART
    {

        public int ID { get; set; }
        public int? pin { get; set; }
        public int konum { get; set; }
        public int? isaret { get; set; }
        public int? imgidx { get; set; }
        public Guid? toplu_islem_UQ { get; set; }
        public bool kodaktif { get; set; }
        public string stokkod { get; set; }
        public long? barkod1 { get; set; }
        public long? barkod2 { get; set; }
        public long? barkod3 { get; set; }
        public string stokadi { get; set; }
        public string stokekkod { get; set; }
        public string stokekadi { get; set; }
        public string transfer_kodu { get; set; }
        public short stokbirim { get; set; }
        public short stokcinsi { get; set; }
        public int? grupkod { get; set; }
        public double? icerik { get; set; }
        public short alistip { get; set; }
        public short satistip { get; set; }
        public bool? rprenvtip { get; set; }
        public int IDKDVtablo { get; set; }
        public int IDMUHtablo { get; set; }
        public int? IDmarka { get; set; }
        public int? IDmodel { get; set; }
        public int? IDrenk { get; set; }
        public int? IDboyut { get; set; }
        public int? IDstoknitelik { get; set; }
        public short? kalite { get; set; }
        public double? en { get; set; }
        public double? boy { get; set; }
        public double? yuksek { get; set; }
        public double? brutagirlik { get; set; }
        public double? netagirlik { get; set; }
        public int? IDagirlikbirim { get; set; }
        public short? europalkolisay { get; set; }
        public string marka { get; set; }
        public string ulkekodu { get; set; }
        public short? dovizno { get; set; }
        public bool? serinotakip { get; set; }
        public bool? sontarihtakip { get; set; }
        public int? EANkod { get; set; }
        public string gtipno { get; set; }
        public string kab_cinsi { get; set; }
        public int? depoyerikod { get; set; }
        public int? satisyerikod { get; set; }
        public int? katalogyerikod { get; set; }
        public int? listeyerikod { get; set; }
        public int? siparisbilgikod { get; set; }
        public Guid? OTV_UQ { get; set; }
        public int? IDOTV { get; set; }
        public double? OTVkatsayi { get; set; }
        public int? IDOIV { get; set; }
        public decimal? STPorani { get; set; }
        public decimal? Damgaorani { get; set; }
        public decimal? Damgatutari { get; set; }
        public short? vergimetod { get; set; }
        public decimal? vergioran { get; set; }
        public decimal? vergimatrah { get; set; }
        public int? turkodu { get; set; }
        public int? turofset { get; set; }
        public int? IDIntrahandels { get; set; }
        public int? IDMesaj { get; set; }
        public int? IDstokfiyat { get; set; }
        public int? IDdepozito { get; set; }
        public double? puan { get; set; }
        public double? akortdakika { get; set; }
        public string efaturaektbl07 { get; set; }
        public bool? kampanya { get; set; }
        public double? minilkbirim { get; set; }
        public double? minonbirim { get; set; }
        public double? minadet { get; set; }
        public double? maxilkbirim { get; set; }
        public double? maxonbirim { get; set; }
        public double? maxadet { get; set; }
        public double? sipilkbirim { get; set; }
        public double? siponbirim { get; set; }
        public double? sipadet { get; set; }
        public Guid? UQ_uretimsablon1 { get; set; }
        public Guid? UQ_uretimsablon2 { get; set; }
        public int? r_dvcins { get; set; }
        public double? r_dvkuru { get; set; }
        public decimal? r_deger1 { get; set; }
        public decimal? r_deger2 { get; set; }
        public decimal? r_deger3 { get; set; }
        public decimal? r_deger4 { get; set; }
        public decimal? r_deger5 { get; set; }
        public double? hesap1 { get; set; }
        public double? hesap2 { get; set; }
        public double? hesap3 { get; set; }
        public double? hesap4 { get; set; }
        public double? hesap5 { get; set; }
        public bool? kontrol0 { get; set; }
        public bool? kontrol1 { get; set; }
        public bool? kontrol2 { get; set; }
        public bool? kontrol3 { get; set; }
        public bool? kontrol4 { get; set; }
        public long? IDexpimp1 { get; set; }
        public Guid kayitdamga { get; set; }
        public byte[] tarihdamga { get; set; }
        public Guid? baglidamga { get; set; }
        public int? IDtranskayit { get; set; }
        public int? priority { get; set; }
        public int? firmnmbr { get; set; }
        public int? firmyear { get; set; }
        public string firstuser { get; set; }
        public DateTime? firstdate { get; set; }
        public string edituser { get; set; }
        public DateTime? editdate { get; set; }
    }
}
