using System;

namespace OrkaToken.Model.STK
{
    public class STK_STOKBASLIK
    {

        public int ID { get; set; }
        public int? pin { get; set; }
        public int konum { get; set; }
        public int? donusum { get; set; }
        public int? isaret { get; set; }
        public int? imgidx { get; set; }
        public Guid? toplu_islem_UQ { get; set; }
        public short IOdurum { get; set; }
        public short belgetipi { get; set; }
        public short? kdvbelgetipi { get; set; }
        public int? IDfisbaslik { get; set; }
        public int IDplankod { get; set; }
        public string plankod { get; set; }
        public int? IDcarikod { get; set; }
        public int? IDekadres { get; set; }
        public int? muhasebefisno { get; set; }
        public string belgeserino { get; set; }
        public long belgeno { get; set; }
        public DateTime belgetarihi { get; set; }
        public DateTime? vadetarihi { get; set; }
        public DateTime kayittarihi { get; set; }
        public DateTime? envantertarihi { get; set; }
        public DateTime? teslimattarihi { get; set; }
        public DateTime? donembasla { get; set; }
        public DateTime? donembitis { get; set; }
        public short? belgeisaret { get; set; }
        public string belgereferans { get; set; }
        public string belgeaciklamasi { get; set; }
        public int? IDbelgenitelik { get; set; }
        public short? belgeolusmatipi { get; set; }
        public string transfer_kodu { get; set; }
        public int? IDdepoyeri { get; set; }
        public int? IDdepartman { get; set; }
        public int? IDprojehizmet { get; set; }
        public int? IDhazirlayanpersonel { get; set; }
        public int? IDyukleyenpersonel { get; set; }
        public int? IDsiparisalanpersonel { get; set; }
        public int? IDplasiyer { get; set; }
        public int? IDadres { get; set; }
        public int? IDcari { get; set; }
        public int? IDgelirler { get; set; }
        public int? IDgenel { get; set; }
        public int? IDistatistik { get; set; }
        public int? IDsatisyeri { get; set; }
        public int? IDnakliye { get; set; }
        public int? IDajanda { get; set; }
        public int? IDnotdefteri { get; set; }
        public decimal? dvtutar { get; set; }
        public decimal? tutar { get; set; }
        public decimal? satirindirimdvtoplami { get; set; }
        public decimal? satirindirimtoplami { get; set; }
        public decimal? matrahdvilavetutar { get; set; }
        public decimal? matrahilavetutar { get; set; }
        public decimal? netdvtutar { get; set; }
        public decimal? nettutar { get; set; }
        public decimal? OTVdvmatrahi { get; set; }
        public decimal? OTVmatrahi { get; set; }
        public decimal? OTVdvtutari { get; set; }
        public decimal? OTVtutari { get; set; }
        public decimal? OTVdvtevkifat { get; set; }
        public decimal? OTVtevkifat { get; set; }
        public decimal? OIVdvtutari { get; set; }
        public decimal? OIVtutari { get; set; }
        public decimal? STPdvtutari { get; set; }
        public decimal? STPtutari { get; set; }
        public decimal? Damgadvtutari { get; set; }
        public decimal? Damgatutari { get; set; }
        public decimal? KDVdvtutari { get; set; }
        public decimal? KDVtutari { get; set; }
        public decimal? KDVdvtevkifat { get; set; }
        public decimal? KDVtevkifat { get; set; }
        public decimal? KDVdvtahsil { get; set; }
        public decimal? KDVtahsil { get; set; }
        public decimal? satirdvtutar { get; set; }
        public decimal? satirtutar { get; set; }
        public decimal? ilavedvtutar { get; set; }
        public decimal? ilavetutar { get; set; }
        public decimal? maliyetdvtutar { get; set; }
        public decimal? maliyettutar { get; set; }
        public decimal? dvdepozitotutar { get; set; }
        public decimal? tldepozitotutar { get; set; }
        public decimal? eklentidvtoplam { get; set; }
        public decimal? eklentitoplam { get; set; }
        public decimal? komisyondvtoplam { get; set; }
        public decimal? komisyontoplam { get; set; }
        public decimal? VergiDVTutari { get; set; }
        public decimal? VergiTLTutari { get; set; }
        public decimal? kesintidvtutar1 { get; set; }
        public decimal? kesintitutar1 { get; set; }
        public decimal? kesintidvtutar2 { get; set; }
        public decimal? kesintitutar2 { get; set; }
        public decimal? kesintidvtutar3 { get; set; }
        public decimal? kesintitutar3 { get; set; }
        public decimal? kesintidvtutar4 { get; set; }
        public decimal? kesintitutar4 { get; set; }
        public decimal? kesintidvtutar5 { get; set; }
        public decimal? kesintitutar5 { get; set; }
        public decimal? kesintidvtoplam { get; set; }
        public decimal? kesintitoplam { get; set; }
        public decimal? belgetoplam { get; set; }
        public decimal? indirimtoplam { get; set; }
        public decimal? OTVtoplam { get; set; }
        public decimal? OIVtoplam { get; set; }
        public decimal? KDVtoplam { get; set; }
        public decimal? KDVtevkif { get; set; }
        public string KDVchar { get; set; }
        public decimal? depozitotltoplam { get; set; }
        public decimal? depozitodvtoplam { get; set; }
        public decimal belgetutar { get; set; }
        public decimal? yuvarlama { get; set; }
        public decimal? doviztutar { get; set; }
        public short? dovizcinsi { get; set; }
        public decimal? dovizkuru { get; set; }
        public bool? KDVel { get; set; }
        public short? fisdovizcinsi { get; set; }
        public decimal? fisdovizkuru { get; set; }
        public DateTime? fistarihi { get; set; }
        public int? indirimgurubu { get; set; }
        public int? fiyatgrubu { get; set; }
        public int? tevkifatno { get; set; }
        public int? tevkdvislturu { get; set; }
        public bool? efaturami { get; set; }
        public int? ebelgetipi { get; set; }
        public int? efaturasenaryo { get; set; }
        public int? efaturaID { get; set; }
        public int? efaturadurumu { get; set; }
        public string efaturadurumnotu { get; set; }
        public string efaturadosyaadi { get; set; }
        public bool? efaturagonderildi { get; set; }
        public Guid? efaturakayitdamga { get; set; }
        public string efaturanotu { get; set; }
        public string efaturaodemenotu { get; set; }
        public string efaturaodemekosulu { get; set; }
        public string efaturahesapnotu { get; set; }
        public string efaturamuafiyetsebebi { get; set; }
        public string efaturaektbl01 { get; set; }
        public string efaturaektbl04 { get; set; }
        public string efaturaektbl06 { get; set; }
        public string kdvmuafiyetkodu { get; set; }
        public string cari_eposta { get; set; }
        public int? earsiv_sendingtype { get; set; }
        public bool yuklenilen { get; set; }
        public int? IDfisbaslikithal { get; set; }
        public int? ithaldagitimmodeli { get; set; }
        public decimal? ithalmaliyet { get; set; }
        public Guid? ihracat_ithalat_kayitdamga { get; set; }
        public DateTime? taksittarihi { get; set; }
        public int? taksitsayisi { get; set; }
        public double? muhtasarkodu { get; set; }
        public string ihracotvplankod { get; set; }
        public decimal? ihracotvtutar { get; set; }
        public string ihrackdvplankod { get; set; }
        public decimal? ihrackdvtutar { get; set; }
        public string stopajplankod { get; set; }
        public decimal? stopajtutar { get; set; }
        public string damgaplankod { get; set; }
        public string fiseksatirplankod { get; set; }
        public decimal? fiseksatirtltutar { get; set; }
        public short? fiseksatirdovizcinsi { get; set; }
        public decimal? fiseksatirdovizkuru { get; set; }
        public decimal? fiseksatirdvtutar { get; set; }
        public string plankodtedarikci { get; set; }
        public int? IDekadrestedarikci { get; set; }
        public int? r_dvcins { get; set; }
        public double? r_dvkuru { get; set; }
        public decimal? r_deger1 { get; set; }
        public decimal? r_deger2 { get; set; }
        public decimal? r_deger3 { get; set; }
        public decimal? r_deger4 { get; set; }
        public decimal? r_deger5 { get; set; }
        public double? hesap1 { get; set; }
        public double? hesap2 { get; set; }
        public double? hesap3 { get; set; }
        public double? hesap4 { get; set; }
        public double? hesap5 { get; set; }
        public bool? kontrol0 { get; set; }
        public bool? kontrol1 { get; set; }
        public bool? kontrol2 { get; set; }
        public bool? kontrol3 { get; set; }
        public bool? kontrol4 { get; set; }
        public bool? kontrol5 { get; set; }
        public bool? kontrol6 { get; set; }
        public bool? kontrol7 { get; set; }
        public bool? kontrol8 { get; set; }
        public bool? kontrol9 { get; set; }
        public int? prp01 { get; set; }
        public int? prp02 { get; set; }
        public int? prp03 { get; set; }
        public int? prp04 { get; set; }
        public int? prp05 { get; set; }
        public int? prp06 { get; set; }
        public int? prp07 { get; set; }
        public int? prp08 { get; set; }
        public int? prp09 { get; set; }
        public int? prp10 { get; set; }
        public int? prp11 { get; set; }
        public int? prp12 { get; set; }
        public int? prp13 { get; set; }
        public int? prp14 { get; set; }
        public int? prp15 { get; set; }
        public long? IDexpimp1 { get; set; }
        public long? IDexpimp2 { get; set; }
        public long? IDexpimp3 { get; set; }
        public long? IDexpimp4 { get; set; }
        public long? IDexpimp5 { get; set; }
        public Guid kayitdamga { get; set; }
        public byte[] tarihdamga { get; set; }
        public Guid? baglidamga { get; set; }
        public int? IDtranskayit { get; set; }
        public int? priority { get; set; }
        public int? firmnmbr { get; set; }
        public int? firmyear { get; set; }
        public string firstuser { get; set; }
        public DateTime? firstdate { get; set; }
        public string edituser { get; set; }
        public DateTime? editdate { get; set; }
        public int? IDpersonel { get; set; }
        public int? IDkatalog { get; set; }
        public int? IDliste { get; set; }
    }
}
