using System;

namespace OrkaToken.Model.STK
{
    public class STK_STOKSATIR
    {

        public int ID { get; set; }
        public int? pin { get; set; }
        public int konum { get; set; }
        public int? isaret { get; set; }
        public int? imgidx { get; set; }
        public int IDbelgebaslik { get; set; }
        public short IOdurum { get; set; }
        public short? belgetipi { get; set; }
        public DateTime? belgetarihi { get; set; }
        public DateTime? vadetarihi { get; set; }
        public string belgeserino { get; set; }
        public long? belgeno { get; set; }
        public int? IDcarikod { get; set; }
        public int? IDplankod { get; set; }
        public int? donusum { get; set; }
        public int? pozisyon { get; set; }
        public short durum { get; set; }
        public int IDstokno { get; set; }
        public string stokkodu { get; set; }
        public long? barkodu { get; set; }
        public string stokadi { get; set; }
        public string stokekkod { get; set; }
        public int? stokgrubu { get; set; }
        public string ekstraaciklama { get; set; }
        public int? stokbirim { get; set; }
        public int? IDmarka { get; set; }
        public int? IDmodel { get; set; }
        public int? IDrenk { get; set; }
        public int? IDboyut { get; set; }
        public int? IDstoknitelik { get; set; }
        public string ulkekodu { get; set; }
        public string marka { get; set; }
        public string serino { get; set; }
        public int? kalite { get; set; }
        public DateTime? sonkullanmatarih { get; set; }
        public DateTime? teslimattarihi { get; set; }
        public DateTime? envantertarihi { get; set; }
        public double? boyut1 { get; set; }
        public double? boyut2 { get; set; }
        public double? boyut3 { get; set; }
        public double? ilkbirim { get; set; }
        public double? onbirim { get; set; }
        public double? icerik { get; set; }
        public double? brut { get; set; }
        public double? net { get; set; }
        public double? adet { get; set; }
        public double? alan { get; set; }
        public double? hacim { get; set; }
        public double? brutkg { get; set; }
        public double? netkg { get; set; }
        public double? dara { get; set; }
        public int? fiyatgrubu { get; set; }
        public short? dvcinsi { get; set; }
        public decimal? dovizkuru { get; set; }
        public short? girilen_fiyat_tipi { get; set; }
        public decimal? girilen_fiyat { get; set; }
        public decimal? dvfiyat { get; set; }
        public decimal? fiyat { get; set; }
        public decimal? dvtutar { get; set; }
        public decimal? tutar { get; set; }
        public short? girilen_ind_tipi { get; set; }
        public decimal? indiroran1 { get; set; }
        public decimal? indirimdvtutar1 { get; set; }
        public decimal? indirimtutar1 { get; set; }
        public decimal? indiroran2 { get; set; }
        public decimal? indirimdvtutar2 { get; set; }
        public decimal? indirimtutar2 { get; set; }
        public decimal? indiroran3 { get; set; }
        public decimal? indirimdvtutar3 { get; set; }
        public decimal? indirimtutar3 { get; set; }
        public decimal? indiroran4 { get; set; }
        public decimal? indirimdvtutar4 { get; set; }
        public decimal? indirimtutar4 { get; set; }
        public decimal? indiroran5 { get; set; }
        public decimal? indirimdvtutar5 { get; set; }
        public decimal? indirimtutar5 { get; set; }
        public decimal? indirdvtoplam { get; set; }
        public decimal? indirtoplam { get; set; }
        public decimal? serbestoran { get; set; }
        public decimal? serbestdvindirim { get; set; }
        public decimal? serbestindirim { get; set; }
        public decimal? satirindirimdvtoplami { get; set; }
        public decimal? satirindirimtltoplami { get; set; }
        public decimal? matrahdvilavetutar { get; set; }
        public decimal? matrahilavetutar { get; set; }
        public decimal? netdvtutar { get; set; }
        public decimal? nettutar { get; set; }
        public int? IDOTVTablo { get; set; }
        public decimal? OTVdvmatrahi { get; set; }
        public decimal? OTVmatrahi { get; set; }
        public decimal? OTVorani { get; set; }
        public double? OTVmiktar { get; set; }
        public decimal? OTVdvtutari { get; set; }
        public decimal? OTVtutari { get; set; }
        public int? OTVtevkifatno { get; set; }
        public decimal? OTVtevkifatorani { get; set; }
        public decimal? OTVdvtevkifat { get; set; }
        public decimal? OTVtevkifat { get; set; }
        public string matrah_plankod { get; set; }
        public int? IDMUHtablo { get; set; }
        public int? IDKDVTablo { get; set; }
        public int? tevkifatno { get; set; }
        public decimal? KDVorani { get; set; }
        public decimal? KDVdvtutari { get; set; }
        public decimal? KDVtutari { get; set; }
        public decimal? KDVdvtevkifat { get; set; }
        public decimal? KDVtevkifat { get; set; }
        public decimal? KDVdvtahsil { get; set; }
        public decimal? KDVtahsil { get; set; }
        public string efaturamuafiyetsebebi { get; set; }
        public string kdvmuafiyetkodu { get; set; }
        public int? IDOIVTablo { get; set; }
        public decimal? OIVorani { get; set; }
        public double? OIVmiktar { get; set; }
        public decimal? OIVdvtutari { get; set; }
        public decimal? OIVtutari { get; set; }
        public decimal? STPorani { get; set; }
        public decimal? STPdvtutari { get; set; }
        public decimal? STPtutari { get; set; }
        public decimal? Damgaorani { get; set; }
        public decimal? Damgadvtutari { get; set; }
        public decimal? Damgatutari { get; set; }
        public decimal? satirdvtutar { get; set; }
        public decimal? satirtltutar { get; set; }
        public decimal? ilavedvtutar { get; set; }
        public decimal? ilavetutar { get; set; }
        public decimal? maliyetdvfiyat { get; set; }
        public decimal? maliyetdvtutar { get; set; }
        public decimal? maliyetfiyat { get; set; }
        public decimal? maliyettutar { get; set; }
        public decimal? dvdepozitotutar { get; set; }
        public decimal? tldepozitotutar { get; set; }
        public decimal? eklentidvtutar1 { get; set; }
        public decimal? eklentitutar1 { get; set; }
        public decimal? eklentidvtutar2 { get; set; }
        public decimal? eklentitutar2 { get; set; }
        public decimal? komisyonoran1 { get; set; }
        public decimal? komisyondvtutar1 { get; set; }
        public decimal? komisyontutar1 { get; set; }
        public decimal? komisyonoran2 { get; set; }
        public decimal? komisyondvtutar2 { get; set; }
        public decimal? komisyontutar2 { get; set; }
        public decimal? komisyonoran3 { get; set; }
        public decimal? komisyondvtutar3 { get; set; }
        public decimal? komisyontutar3 { get; set; }
        public decimal? komisyondvtoplam { get; set; }
        public decimal? komisyontoplam { get; set; }
        public decimal? DVmatrah { get; set; }
        public decimal? TLmatrah { get; set; }
        public decimal? VergiOrani { get; set; }
        public decimal? VergiDVTutari { get; set; }
        public decimal? VergiTLTutari { get; set; }
        public double gecyukadet { get; set; }
        public decimal gecyukKDVtutari { get; set; }
        public double yuklenadet { get; set; }
        public decimal yuklenKDVtutari { get; set; }
        public double kalanyukadet { get; set; }
        public decimal kalanyukKDVtutari { get; set; }
        public double? ithaloran { get; set; }
        public decimal? ithalmaliyetdvfiyat { get; set; }
        public decimal? ithalmaliyetdvtutar { get; set; }
        public decimal? ithalmaliyetfiyat { get; set; }
        public decimal? ithalmaliyettutar { get; set; }
        public int? turkodu { get; set; }
        public decimal? kesintioran1 { get; set; }
        public decimal? kesintidvtutar1 { get; set; }
        public decimal? kesintitutar1 { get; set; }
        public decimal? kesintioran2 { get; set; }
        public decimal? kesintidvtutar2 { get; set; }
        public decimal? kesintitutar2 { get; set; }
        public decimal? kesintioran3 { get; set; }
        public decimal? kesintidvtutar3 { get; set; }
        public decimal? kesintitutar3 { get; set; }
        public decimal? kesintioran4 { get; set; }
        public decimal? kesintidvtutar4 { get; set; }
        public decimal? kesintitutar4 { get; set; }
        public decimal? kesintioran5 { get; set; }
        public decimal? kesintidvtutar5 { get; set; }
        public decimal? kesintitutar5 { get; set; }
        public double? puan { get; set; }
        public int? taksitsayisi { get; set; }
        public int? IDdepo { get; set; }
        public int? IDdepartman { get; set; }
        public int? IDplasiyer { get; set; }
        public int? IDprojehizmet { get; set; }
        public int? IDadres { get; set; }
        public int? IDcari { get; set; }
        public int? IDgelirler { get; set; }
        public int? IDgenel { get; set; }
        public int? IDistatistik { get; set; }
        public int? IDsatisyeri { get; set; }
        public int? IDpersonel { get; set; }
        public int? IDnakliye { get; set; }
        public int? IDkatalog { get; set; }
        public int? IDliste { get; set; }
        public string kab_cinsi { get; set; }
        public string kab_no { get; set; }
        public double? kab_adeti { get; set; }
        public string kab_markasi { get; set; }
        public int? Iliskili_Satir_ID { get; set; }
        public int? r_dvcins { get; set; }
        public double? r_dvkuru { get; set; }
        public decimal? r_deger1 { get; set; }
        public decimal? r_deger2 { get; set; }
        public decimal? r_deger3 { get; set; }
        public decimal? r_deger4 { get; set; }
        public decimal? r_deger5 { get; set; }
        public bool? kontrol0 { get; set; }
        public bool? kontrol1 { get; set; }
        public bool? kontrol2 { get; set; }
        public bool? kontrol3 { get; set; }
        public bool? kontrol4 { get; set; }
        public int? k1 { get; set; }
        public int? k2 { get; set; }
        public int? k3 { get; set; }
        public int? k4 { get; set; }
        public int? k5 { get; set; }
        public double? c1 { get; set; }
        public double? c2 { get; set; }
        public double? c3 { get; set; }
        public double? c4 { get; set; }
        public double? c5 { get; set; }
        public long? IDexpimp1 { get; set; }
        public long? IDexpimp2 { get; set; }
        public long? IDexpimp3 { get; set; }
        public long? IDexpimp4 { get; set; }
        public long? IDexpimp5 { get; set; }
        public Guid? UQ_stoksatir { get; set; }
        public Guid? UQ_uretimbaslik { get; set; }
        public Guid? UQ_uretimsablon1 { get; set; }
        public Guid? UQ_uretimsablon2 { get; set; }
        public Guid kayitdamga { get; set; }
        public byte[] tarihdamga { get; set; }
        public Guid? baglidamga { get; set; }
        public int? IDtranskayit { get; set; }
        public int? priority { get; set; }
        public int? firmnmbr { get; set; }
        public int? firmyear { get; set; }
        public string firstuser { get; set; }
        public DateTime? firstdate { get; set; }
        public string edituser { get; set; }
        public DateTime? editdate { get; set; }
        public int? tevkdvislturu { get; set; }
        public double? ktrl_adet { get; set; }
    }
}
