using System;

namespace OrkaToken.Model.ORT
{
    public class ORT_FISSATIR
    {

        public int ID { get; set; }
        public int? pin { get; set; }
        public int konum { get; set; }
        public int? isaret { get; set; }
        public int? imgidx { get; set; }
        public int? IDFisbaslik { get; set; }
        public DateTime fisbelgedonemi { get; set; }
        public short? fisbelgetipi { get; set; }
        public short? kdvbelgetipi { get; set; }
        public short? belgeadeti { get; set; }
        public int? Hesapkebirkodu { get; set; }
        public int? IDHesapkodu { get; set; }
        public string hesapkodu { get; set; }
        public int? IDkarsihesapkodu { get; set; }
        public string karsihesapkodu { get; set; }
        public DateTime? fisbelgetarihi { get; set; }
        public DateTime? fisbelgevadesi { get; set; }
        public string belgeserino { get; set; }
        public long? fisbelgeno { get; set; }
        public string fisaciklamasi { get; set; }
        public string fisbelgereferans { get; set; }
        public string odemeyontemi { get; set; }
        public string bilstokkod { get; set; }
        public decimal? tlfiyat { get; set; }
        public decimal? abmiktar { get; set; }
        public decimal? abborctutar { get; set; }
        public decimal? abalactutar { get; set; }
        public short? dovizcinsi { get; set; }
        public decimal? dvfiyat { get; set; }
        public decimal? dovizkuru { get; set; }
        public decimal? dvmiktar { get; set; }
        public decimal? dvborctutar { get; set; }
        public decimal? dvalactutar { get; set; }
        public decimal? tlborctutar { get; set; }
        public decimal? tlalactutar { get; set; }
        public short? borcalacak { get; set; }
        public int? IDKDVTablo { get; set; }
        public int? tevkdvislturu { get; set; }
        public int? tevkifattipi { get; set; }
        public decimal? kdvoran { get; set; }
        public decimal KDVtutari { get; set; }
        public int? IDOTVTablo { get; set; }
        public string hesapaltbirim { get; set; }
        public decimal? hesapmiktar { get; set; }
        public double gecyukadet { get; set; }
        public decimal gecyukKDVtutari { get; set; }
        public double yuklenadet { get; set; }
        public decimal yuklenKDVtutari { get; set; }
        public double kalanyukadet { get; set; }
        public decimal kalanyukKDVtutari { get; set; }
        public decimal? gec_ithaltutar { get; set; }
        public double? gec_ithaloran { get; set; }
        public decimal? ithalmaliyet { get; set; }
        public double? ilkdeger { get; set; }
        public double? sondeger { get; set; }
        public double? aradeger { get; set; }
        public short? altbirimi { get; set; }
        public string adresfirmakodu { get; set; }
        public int? IDFisnotu { get; set; }
        public double? puan { get; set; }
        public int? grpgenel { get; set; }
        public int? grpadres { get; set; }
        public int? grpcari { get; set; }
        public int? grpplasiyer { get; set; }
        public int? grppersonel { get; set; }
        public int? grpnakliye { get; set; }
        public int? grpgelirler { get; set; }
        public int? grpdepartman { get; set; }
        public int? grpprojehizmet { get; set; }
        public int? grpistatistik { get; set; }
        public int? grpkatalog { get; set; }
        public int? grpliste { get; set; }
        public int? isletmedefterineyaz { get; set; }
        public int? hesapturu { get; set; }
        public decimal? alisgidertutar { get; set; }
        public decimal? satisgelirtutar { get; set; }
        public decimal? geneltoplam { get; set; }
        public decimal? tevkifattutar { get; set; }
        public decimal? kredikartitutar { get; set; }
        public string kdvhesapkodu { get; set; }
        public string tevkifathesapkodu { get; set; }
        public string kredikartihesapkodu { get; set; }
        public string tahakkukhesapkodu { get; set; }
        public bool? tahakkukmuhasebe { get; set; }
        public int? defterbeyankodu { get; set; }
        public double? kayitsirano { get; set; }
        public int? r_dvcins { get; set; }
        public double? r_dvkuru { get; set; }
        public decimal? r_deger1 { get; set; }
        public decimal? r_deger2 { get; set; }
        public decimal? r_deger3 { get; set; }
        public decimal? r_deger4 { get; set; }
        public decimal? r_deger5 { get; set; }
        public decimal? r_deger6 { get; set; }
        public decimal? r_deger7 { get; set; }
        public decimal? r_deger8 { get; set; }
        public decimal? r_deger9 { get; set; }
        public decimal? r_deger10 { get; set; }
        public bool? kontrol0 { get; set; }
        public bool? kontrol1 { get; set; }
        public bool? kontrol2 { get; set; }
        public bool? kontrol3 { get; set; }
        public bool? kontrol4 { get; set; }
        public long? IDexpimp1 { get; set; }
        public long? IDexpimp2 { get; set; }
        public long? IDexpimp3 { get; set; }
        public long? IDexpimp4 { get; set; }
        public long? IDexpimp5 { get; set; }
        public int? prp01 { get; set; }
        public int? prp02 { get; set; }
        public int? prp03 { get; set; }
        public int? prp04 { get; set; }
        public int? prp05 { get; set; }
        public int? prp06 { get; set; }
        public int? prp07 { get; set; }
        public int? prp08 { get; set; }
        public int? prp09 { get; set; }
        public int? prp10 { get; set; }
        public int? prp11 { get; set; }
        public int? prp12 { get; set; }
        public int? prp13 { get; set; }
        public int? prp14 { get; set; }
        public int? prp15 { get; set; }
        public Guid kayitdamga { get; set; }
        public byte[] tarihdamga { get; set; }
        public Guid? baglidamga { get; set; }
        public int? IDtranskayit { get; set; }
        public int? priority { get; set; }
        public int? firmnmbr { get; set; }
        public int? firmyear { get; set; }
        public string firstuser { get; set; }
        public DateTime? firstdate { get; set; }
        public string edituser { get; set; }
        public DateTime? editdate { get; set; }
        public int? grpdepoyeri { get; set; }
        public int? grpsatisyeri { get; set; }
    }
}
