using System;

namespace OrkaToken.Model
{
    public class GNL_FIRMATANIM
    {

        public int ID { get; set; }
        public int? pin { get; set; }
        public int? isaret { get; set; }
        public int? imgidx { get; set; }
        public Guid? toplu_islem_UQ { get; set; }
        public int? guncelno { get; set; }
        public int? subetanimi { get; set; }
        public string veritabaniadi { get; set; }
        public int konum { get; set; }
        public string unvan1 { get; set; }
        public string unvan2 { get; set; }
        public string soyadi { get; set; }
        public int? vergidairekod { get; set; }
        public string vergidairesi { get; set; }
        public string vergino { get; set; }
        public string tckimliknr { get; set; }
        public string mernisno { get; set; }
        public string ticaretsicilno { get; set; }
        public string adres1 { get; set; }
        public string adres2 { get; set; }
        public string binaadi { get; set; }
        public string binano { get; set; }
        public string kapino { get; set; }
        public string kasabakoy { get; set; }
        public string semt { get; set; }
        public string ilce { get; set; }
        public string il { get; set; }
        public int? ilcekodu { get; set; }
        public int? postakod { get; set; }
        public short? ulkekodu { get; set; }
        public string adresno { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string gsm { get; set; }
        public string fax { get; set; }
        public string eposta { get; set; }
        public string webadresi { get; set; }
        public string firmakisakod { get; set; }
        public int? IDSMMM { get; set; }
        public int? IDYMM { get; set; }
        public int? IDduzenleyen { get; set; }
        public int? IDkanunitemsilci { get; set; }
        public int? muhucretbrutnet { get; set; }
        public decimal? muhasebeucreti { get; set; }
        public string muhasebehizmetnevi { get; set; }
        public string muhasebehizmetsure { get; set; }
        public DateTime? muhasebesozlesmetarihi { get; set; }
        public string muhasebesozlesmeno { get; set; }
        public DateTime? sozbasladonemi { get; set; }
        public DateTime? sozbitisdonemi { get; set; }
        public string isveyahizmetnevi { get; set; }
        public string orkasifre { get; set; }
        public int? beyankdvdonem { get; set; }
        public int? beyankdv2donem { get; set; }
        public int? beyandeftertur { get; set; }
        public int? beyanmuhtasardonem { get; set; }
        public int? beyanfirmatur { get; set; }
        public int? beyanfaliyetkod { get; set; }
        public int? beyananafaliyet { get; set; }
        public int? beyanmeslekgrupkod { get; set; }
        public string beyanmeslektes { get; set; }
        public string beyanmeslektesno { get; set; }
        public string beyanbagkurno { get; set; }
        public int? fisnumaralamaduzeni { get; set; }
        public int? fisnumaralamatipi { get; set; }
        public DateTime? donembasla { get; set; }
        public DateTime? donembitis { get; set; }
        public bool? kontrol0 { get; set; }
        public bool? kontrol1 { get; set; }
        public bool? kontrol2 { get; set; }
        public bool? kontrol3 { get; set; }
        public bool? kontrol4 { get; set; }
        public short? orkaweb_kullanim_tipi { get; set; }
        public bool? aktifpasif { get; set; }
        public string firmaunvan { get; set; }
        public string subekisaadi { get; set; }
        public int? ticaretsicilmudur { get; set; }
        public bool? edefteruygulamasinatabi { get; set; }
        public bool? efaturauygulamasinatabi { get; set; }
        public string sskmudurlukadi { get; set; }
        public DateTime? sskacilistarihi { get; set; }
        public DateTime? sskkapanistarihi { get; set; }
        public int? meslekgrupkod { get; set; }
        public string ssk_m { get; set; }
        public string ssk_iskolu { get; set; }
        public string ssk_unite { get; set; }
        public string ssk_yeni { get; set; }
        public string ssk_sirano { get; set; }
        public string ssk_il { get; set; }
        public string ssk_ilce { get; set; }
        public string ssk_kont { get; set; }
        public string aracikodu { get; set; }
        public string calbol_m { get; set; }
        public string calbol_iskolu { get; set; }
        public string calbol_sirano { get; set; }
        public string calbol_il { get; set; }
        public string iskuradi { get; set; }
        public string iskurno { get; set; }
        public int? serbestbolgekodu { get; set; }
        public int? isyerituru { get; set; }
        public int? isyerikodu { get; set; }
        public int? isyerimulkiyetdurumu { get; set; }
        public Guid kayitdamga { get; set; }
        public byte[] tarihdamga { get; set; }
        public Guid? baglidamga { get; set; }
        public int? IDtranskayit { get; set; }
        public int? priority { get; set; }
        public int? firmnmbr { get; set; }
        public int? firmyear { get; set; }
        public string firstuser { get; set; }
        public DateTime? firstdate { get; set; }
        public string edituser { get; set; }
        public DateTime? editdate { get; set; }
    }
}
